spring:
  application:
    name: eureka-server-01
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enableSelfPreservation: false

