eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: user-service-02
spring:
  application:
    name: client
server:
  port: 9001

