eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: user-service-01
spring:
  application:
    name: user-service
server:
  port: 9002

