eureka:
  instance:
    hostname: locahost
    instanceId: client-7001
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client
server:
  port: 7001
